# Generated by Django 5.1 on 2024-09-09 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
        ('notes', '0002_collaborator_note_collaborator'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='notes', to='label.label'),
        ),
    ]
