# Generated by Django 5.1 on 2024-09-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'log',
            },
        ),
    ]
